language: python
sudo: false
python:
    - '2.7'
    - '3.2'
    - '3.3'
    - '3.4'
    - '3.5'
install:
    - ./travis-build.sh
    - pip install coveralls
script: ./travis-run.sh
after_success:
    - coveralls
